### ISSUE TITLE
Possible issue on Monterey: nothing being copied

### ISSUE THREAD

**Issue by cablehead** [cablehead/stacks#32]
MaxGaav from Reddit saw this issue:

> Downloaded the Intel version, on Monterey. Opens, shows up in the menubar but does not copy anything.

https://www.reddit.com/r/macapps/comments/13xg34c/comment/kazoed9/?utm_source=share&utm_medium=web2x&context=3

If anyone else comes across this, a reproduction would be super helpful.

**Comment by VKondakoff** [comment]
> If anyone else comes across this, a reproduction would be super helpful.

Here am I. 

<img width="153" alt="Снимок экрана 2024-05-31 в 04 03 59" src="https://github.com/cablehead/stacks/assets/230824/ab063bb5-73eb-4f8f-9117-d3fda3a35059">


Monterey 12.7.5

**Comment by cablehead** [comment]
Appreciate the feedback, and good idea. The combo of these two issues should help:

- https://github.com/cablehead/stacks/issues/69
- https://github.com/cablehead/stacks/issues/67
