### ISSUE TITLE
Suggestion: A rust crate About Cross-platform clipboard API (text | image | rich text | html | files | monitoring changes)

### ISSUE THREAD

**Issue by ChurchTao** [cablehead/stacks#55]
I really like the stacks UI and I want it to get better. I thought my crate might be helpful to you. 😄

Let me self-recommend my crate.
Clipboard API (text | image | rich text | html | files | monitoring changes)
https://github.com/ChurchTao/clipboard-rs

**Comment by ChurchTao** [comment]
@cablehead 
If you need it, I can also take time to help you improve this project.

**Comment by ChurchTao** [comment]
@cablehead 
I see what you mean, but there are a few difficult points here. And it is not recommended to do so
1. Obtaining all formats at once and performing Base64 conversion will cause a certain performance loss and unnecessary memory consumption.
2. You may not need all the formats on the clipboard, you only need those formats such as plain text, pictures, Html and so on, if you really need other format, you can use the api `available_formats()=>Vec<String> ` to get all formats clipboard have and use `getBuffer(&str: format)` to get `vec[u8]`.
3. `changeCount` is just a method of monitoring clipboard changes in macOS. In Linux and Windows, it is not monitored in this form, so there is no way to unify them into `changeCount`.
4. I think the field `source` is great, but I need to explore the feasibility of different platforms, which I haven't explored before.

**Comment by cablehead** [comment]
Thanks for the reply @ChurchTao! I'm away this week, but will follow up more when I get back. Quickly though `available_formats()=>Vec<String>` may offer what I'm hoping for as-is! re, `changeCount`, right that makes sense. I'm not looking to get the same fields as macOS provides everywhere, rather, make what the platform offers available, and then let the user (plugin authors) work with that, as they like.

**Comment by ChurchTao** [comment]
@cablehead Thanks for reply!
I understand, what you mean is that you want to get all the details returned by the platform interface as much as possible, and users can choose according to their own needs. It is indeed a great idea, which increases flexibility. However, according to my idea, through `available_formats` and `get_buffer`, at least the data is lossless, and a certain format will not be lost. I sincerely ask here, if you want to meet your needs, what form of API would you expect? When you come back when you are free, we can have a good discussion.

**Comment by cablehead** [comment]
@ChurchTao if you're able, it'd be great to have you stop by the [Stacks discord](https://discord.com/invite/YNbScHBHrh), to keep chatting. No pressure though, we can keep chatting here too

**Comment by ChurchTao** [comment]
👌
