### ISSUE TITLE
fix: Clicking an URL in Meta Panel does nothing

### ISSUE THREAD

**Issue by VKondakoff** [cablehead/stacks#74]
Stacks 0.15.8

Clicking an URL in Meta Panel does nothing:

<img width="429" alt="Снимок экрана 2024-06-01 в 12 02 41" src="https://github.com/cablehead/stacks/assets/230824/dc3bcb4f-2262-4a17-91d9-6fbb7bb391b8">

(I was expecting to see the URL to be open in the default browser).

**Comment by cablehead** [comment]
You're right! Hrm that did use to work. Should be an easy fix...
