### ISSUE TITLE
If you click `Enter` when there is a stack selected in Nav pane the content of the clipboard will be filled with the stack name

### ISSUE THREAD

**Issue by VKondakoff** [cablehead/stacks#75]
If you click `Enter` when there is a stack selected in Nav pane the content of the clipboard will be filled with the stack name.

<img width="672" alt="Снимок экрана 2024-06-03 в 15 46 30" src="https://github.com/cablehead/stacks/assets/230824/73183987-630f-4986-ac60-806150d98ed6">

Here it is. If I click `Enter` now the name of the stack (`Stacks info`) will go to the clipboard instead of the clip content. Thus, when using `Alt-arrows` one should always use `right arrow` before trying to copy clip to the clipboard.

**Comment by cablehead** [comment]
Right, this bugs the be-jeepers out of me 😆. I think generally all actions should target the selected clip in a stack, and never the actual stack, even if the stack is the main focus: unless the action is stack specific..

**Comment by cablehead** [comment]
the fix for this one: enter copies the content of the current clip, even if the main focus is the stack
