### ISSUE TITLE
Stacks hangs if you add text to the clip, which content type is set to `link` without changing it's content type

### ISSUE THREAD

**Issue by VKondakoff** [cablehead/stacks#76]
Steps to reproduce:
1. Copy `https://github.com/cablehead/stacks` to clipboard (the clip content type is automatically set to `link`)
2. Press `Ctrl-Enter` to edit clip
3. Add some text to the beginning of the clip (say, "Some title" and "Enter" to make new line)
<img width="722" alt="Снимок экрана 2024-06-04 в 23 07 55" src="https://github.com/cablehead/stacks/assets/230824/3715bf1a-bac7-4f4e-a2ef-242603c3a765">

4. Press `Ctrl-Enter` to capture edit
5. Try to use arrows up/down or any of keyboard hotkeys - Stacks does not respond.

I'm pretty sure this is because I added text to clip which content type was set to link without changing the content type back to `text`.

If you restart Stacks the clip type appears as text:
<img width="722" alt="Снимок экрана 2024-06-04 в 23 12 48" src="https://github.com/cablehead/stacks/assets/230824/83207481-f380-44e2-91d5-04932ee11a25">

But if you scroll to the clip which content type is set wrong (as the last clip in this scrinshot) Stacks will hang again:

<img width="722" alt="Снимок экрана 2024-06-04 в 23 15 03" src="https://github.com/cablehead/stacks/assets/230824/093ef630-3127-4429-9f75-338054e1a7f1">

**Comment by cablehead** [comment]
great catch 🙏🏻
